cs50/cs50/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

cs50/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name = "index"),
    path("<str:name>", views.greet, name = "greet"),
    path("eddie/", views.eddie, name = "eddie")
    
]

cs50/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

cs50/tasks/urls.py
from django.urls import path
from . import views

app_name = "task"

urlpatterns = [
    path("", views.index, name = "index"),
     path("add/", views.add, name = "add"),
]

cs50/hello/models.py
from django.db import models

# Create your models here.

cs50/newyear/models.py
from django.db import models

# Create your models here.

cs50/tasks/models.py
from django.db import models

# Create your models here.

cs50/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def eddie(request):
    return HttpResponse("hello eddie")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

cs50/newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()

    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.date == 1
    })

cs50/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

#tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label = "New Task")
    priority = forms.IntegerField(label = "Prioroty", min_value=1, max_value=10)


def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request, "tasks/add.html",{
                "form": form
            })

    
    return render(request, "tasks/add.html",{
        "form": NewTaskForm()
    })

cs50/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>link</title>
    </head>
    <body>
        <h1>
            hello , {{ name }} !
        </h1>
    </body>
</html>    

cs50/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>link</title>
        <style>
            div {
                border: 5px solid black;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 100px;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div>
            hello bitch
        </div>
        no style bitch
    </body>
</html>    

cs50/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>is it new year</title>
        <link href="{% static 'newyear/style.css'%}" rel="stylesheet">
    </head>
    <body>
        <div id="yeee">
            {% if newyear %}
                <h1>
                    YES
                </h1>
            {% else %}
                <h1>
                    NO
                </h1>
            {% endif %}
        </div>
    </body>
</html>    

cs50/tasks/templates/tasks/add.html
{% extends "tasks/layout.html"%}
        
{% block body %}
<h1>add task</h1>
<form action="{% url 'task:add' %}" method = "POST">
    {% csrf_token %}
    {{form}}
    <input type = "submit">
</form>
<a href="{% url 'task:index' %}">back to menu</a>
{% endblock %}

cs50/tasks/templates/tasks/index.html
{% extends "tasks/layout.html"%}
        
{% block body %}
<ul>
    {% for task in tasks %}
    <li>
        {{task}}
    </li>
    {% empty %}
    <li>No task</li>
    {% endfor %}
</ul>
<a href="{% url 'task:add' %}">Add a new task</a>
{% endblock %}

cs50/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>tasks</title>
    </head>
    <body>
       {% block body %}
       {% endblock %}
    </body>
</html>    